sirclo-solution/template-rose

package.json
Minta tolong direview ya thank you
=> fix: update nexus version 2.5.3

pages/[lng]/index.tsx, pages/[lng]/products/index.tsx, public/scss/components/Product.module.scss
=> fix(productcard): limit and truncate category on product card

public/scss/pages/Blog.module.scss, public/scss/pages/PaymentNotif.module.scss
turun karena menggunakan absolute, sehingga ketika payment berubah jumlah nya dia berubah.
Update: pakai flex, pindahin styling dari textnya ke form inputnya, truncate text kalau nama file kepanjangan,
firefox desktop
Safari iphone 13 max
Blog kosong
removeicon no longer absolute
=> fix(paymentconfirmation): uploaded image remove button, fix(blog): full height for container

lib/handleWebVitals.ts, locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, pages/[lng]/payment_method/index.tsx, pages/[lng]/place_order/index.tsx, pages/[lng]/review/[id].tsx, pages/[lng]/shipping_method/index.tsx, pages/_app.js, public/scss/components/CustomerDetail.module.scss, public/scss/components/Maintenance.module.scss, public/scss/components/Map.module.scss
Map pin point 
-account
-place order
-shpping method
Webvitals tracker
Maintenance page
-default
-custom
=> add webvitals tracker, map pin point, buyerHideNameSliderClassName, fix maintenance page, remove ts-ignore

public/scss/components/Maintenance.module.scss
Maintenance page
Default :
Custom :
=> fix: custom maintenance page

components/GoogleTagManager/index.tsx, components/Layout/Layout.tsx, components/Newsletter/index.tsx, locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, pages/[lng]/login/index.tsx, pages/[lng]/register/index.tsx, public/scss/components/Newsletter.module.scss, public/scss/pages/Account.module.scss
**PopUp:**
https://user-images.githubusercontent.com/38358288/186843851-e0e7d59e-5298-4c20-8870-d8b53c58dc61.mp4
**Group Membership**
**Locales TermsAndConditions:**
**GTM:**
=> feat: GTM, Popup Newsletter V2, Group Membership, Bump 2.12.3

components/Layout/Layout.tsx
https://user-images.githubusercontent.com/38358288/187588897-6e09e5bc-edff-430e-80b4-ed182e97fc84.mp4
=> fix: remove overlay when newsletter unactive

components/Header/index.tsx
=> fix(Header): change H3 headerTitle to H1

components/Newsletter/index.tsx, components/OrderSummaryBox/index.tsx, locales/en.json, locales/id.json, pages/[lng]/payment_method/index.tsx, public/scss/components/OrderSummaryBox.module.scss, public/scss/components/Shipping.module.scss
Cart
**Place Order**
**Shipping Method**
**Payment**
updated coupon :
=> feat: moreShipping, shipperLogo

locales/en.json, locales/id.json, pages/[lng]/legal/[slug].tsx, pages/[lng]/login/index.tsx, public/scss/components/Disclaimer.module.scss, public/scss/pages/Contact.module.scss, public/scss/pages/Legal.module.scss, public/scss/pages/Login.module.scss
**Screenshots:**
- Legal page
- Contact page
- Login by whatsapp
- Login by email
- Register by whatsapp
- Register by email
- Cart
**Update**
- Legal Categories
- Legal Category Hover
=> feat: add legal page and replace wording for login, register, and contact pages

package.json, pages/[lng]/products/[slug].tsx, public/scss/components/Product.module.scss
```
This pull request includes:
- Bump nexus to 2.17.4
- Implement product section highlight page
```
Task: https://phabricator.sirclo.com/T42238
=> feat(product-highlight): add product list page

package.json, pages/[lng]/index.tsx, public/scss/components/Button.module.scss, public/scss/components/Placeholder.module.scss, public/scss/components/Product.module.scss, public/scss/components/ProductCategory.module.scss
**Display 1**
**Display 2**
Admin Panel
=> feat(homepage): add product highlight and category

locales/en.json, locales/id.json, package.json, pages/[lng]/account/index.tsx, pages/[lng]/index.tsx, pages/[lng]/products/[slug].tsx, pages/_app.js
https://user-images.githubusercontent.com/8079082/210763957-a1ad3c85-b893-4b5d-9304-33541d9163e9.mp4
=> chore: bump to 2.17.12, breaking changes and featureflag producthighlight

components/BottomNavigation/index.tsx, components/Copyright/index.tsx, components/Footer/Footer.tsx, components/Layout/Layout.tsx, locales/en.json, locales/id.json, pages/[lng]/account/index.tsx, pages/[lng]/article/[slug].tsx, pages/[lng]/cart/index.tsx, pages/[lng]/categories/index.tsx, pages/[lng]/contact/index.tsx, pages/[lng]/forgot-password/index.tsx, pages/[lng]/gift-card/index.tsx, pages/[lng]/index.tsx, pages/[lng]/login/index.tsx, pages/[lng]/payment_notif/[[...orderID]].tsx, pages/[lng]/place_order/payment/[[...orderID]].tsx, pages/[lng]/products/[slug].tsx, pages/[lng]/products/index.tsx, pages/[lng]/register/index.tsx, pages/[lng]/reset-password/index.tsx, pages/[lng]/search/index.tsx, pages/[lng]/testimonials/index.tsx, pages/[lng]/thank-you/[[...orderID]].tsx, public/scss/components/Copyright.module.scss, public/scss/components/Footer.module.scss, public/scss/components/SocialMediaIcons.module.scss, public/scss/components/Widget.module.scss
**Task** : https://phabricator.sirclo.com/T43800
**Figma** : https://www.figma.com/file/cl2GPB5tKKSNjA5CxPsJBB/%F0%9F%9F%A2-%5BVENDOR%5D-Ros%C3%A9?node-id=3484%3A15593&t=nutzMOivBRYwqbyb-4
**Before**
**Footer with Main Footer Text**
**Footer with Main Footer Image**
**Footer Newsletter Section Functionality**
https://drive.google.com/file/d/1wjISbR3qXgxHe6y4t3-7kDKqcqvGtvm4/view?usp=share_link
=> fix(footer): add widget footer link

pages/[[...param]].tsx
this solution is directly tested using staging URL with https://httpstatus.io/.
PoW template is running well:
=> fix(redirect): adjust redirect on file [[...param]].tsx

pages/[[...param]].tsx
Cherry-pick commits from PR: https://github.com/sirclo-solution/template-rose/pull/50
=> Release prod 20230123

components/BottomNavigation/index.tsx, components/Copyright/index.tsx, components/Footer/Footer.tsx, components/Layout/Layout.tsx, locales/en.json, locales/id.json, pages/[lng]/account/index.tsx, pages/[lng]/article/[slug].tsx, pages/[lng]/cart/index.tsx, pages/[lng]/categories/index.tsx, pages/[lng]/contact/index.tsx, pages/[lng]/forgot-password/index.tsx, pages/[lng]/gift-card/index.tsx, pages/[lng]/index.tsx, pages/[lng]/legal/[slug].tsx, pages/[lng]/login/index.tsx, pages/[lng]/payment_notif/[[...orderID]].tsx, pages/[lng]/place_order/payment/[[...orderID]].tsx, pages/[lng]/products/[slug].tsx, pages/[lng]/products/index.tsx, pages/[lng]/register/index.tsx, pages/[lng]/reset-password/index.tsx, pages/[lng]/search/index.tsx, pages/[lng]/testimonials/index.tsx, pages/[lng]/thank-you/[[...orderID]].tsx, public/scss/components/Copyright.module.scss, public/scss/components/Footer.module.scss, public/scss/components/SocialMediaIcons.module.scss, public/scss/components/Widget.module.scss
Cherry-pick commits from PR:
- https://github.com/sirclo-solution/template-rose/pull/48
- https://github.com/sirclo-solution/template-rose/pull/52
**Sanity check:**
=> Release prod 20230125

locales/id.json, pages/[lng]/shipping_method/index.tsx
adjust locale: 
hide cart notes on shipping method page:
=> fix(product-notes): adjust locales and delete cart notes on shipping method page

locales/en.json, locales/id.json
Benerin issue ini:
https://phabricator.sirclo.com/T44236#1027228
=> fix(account): add wording for point in order history summary

package.json, public/scss/components/EstimateShipping.module.scss
- Fix custom shipping when cost 0 (2.19.2)
- Fix discountedCost.value undefined in Custom Shipping (2.19.1)
<html>
<body>
Item test | Proof of work
--  | -- 
Custom Shipping 0  | ![Rose Theme - Pesanan - Google Chrome 15_05_2023 12_52_32](https://github.com/sirclo-solution/template-rose/assets/16263184/684e4bb8-73fb-4681-b652-1ef0389c814d) ![Rose Theme - Pesanan - Google Chrome 15_05_2023 13_15_19](https://github.com/sirclo-solution/template-rose/assets/16263184/848fc4e0-baa2-41df-b8ce-81b6b317589f)
Custom Shipping not 0 |  ![Rose Theme - Pesanan - Google Chrome 15_05_2023 12_52_47](https://github.com/sirclo-solution/template-rose/assets/16263184/dc0ca0b3-6361-446e-9e11-1ec4a35bdd1a) ![Rose Theme - Pesanan - Google Chrome 15_05_2023 …
=> chore: bump 2.19.2 and fix styling for logo custom shipping

components/OrderSummaryBox/index.tsx, locales/id.json, public/scss/components/OrderSummaryBox.module.scss
Figma:
https://www.figma.com/file/srLjsAPJpqwO1MFnOgDWk2/Rose-v.02?type=design&node-id=1401-8723&t=mI29XLRgutVQX3RL-0
**[ID]**
Applied point:
Point popup:
Insufficient point:
**[EN]**
Applied point:
Point popup:
Insufficient point:
=> fix(order-summary): styling popup point

package.json
=> chore bump 2.19.5

package.json
task : https://phabricator.sirclo.com/T55230
=> chore: bump nexus 2.19.33
